### ISSUE TITLE
Possible to set transition used when navigating?

### ISSUE THREAD

**Issue by garlandcrow** [cdellacqua/svelte-stack-router#10]
This project looks like the perfect fit for my ideal stack for doing some mobile app programming on iOS/Android. I have a setup using Capacitor+Svelte(vite), but since I really don't need any fancy sveltekit/routify type features, this seems perfect for handling that mobile app use case. The transitions also look really good for having that mobile experience as well. I was wondering if it's possible to set the transition animation during navigation somehow? So if you had a tabbar type interface and are switching tabs you could switch the animation to slide in from the left or right depending on which tab you are transitioning to/from. Maybe this is easily done already?

**Comment by cdellacqua** [comment]
The transition animation is customizable, a "slide" and a "dive" animation are provided out-of-the-box.

The default behavior of the "slide" transition is to move right or left based on whether the navigation is forward or backward (like it would in an native App).

Considering your scenario you could create a custom transition using the "slide" function [you can find here](https://github.com/cdellacqua/svelte-stack-router/blob/master/src-ts/transition-functions.ts) to match the desired behavior.
