### ISSUE TITLE
Vite HMR error when using svelte-stack-router lifecycle hook

### ISSUE THREAD

**Issue by PhouvanhKCSV** [cdellacqua/svelte-stack-router#12]
I create Svelte app using Vite (Svelte Typescript preset) and install svelte-stack-router@2.4.6
It works fine when the app initial load, but when i edit the route component, i got the following error, so i have to reload the window to make it work.
```
[HMR][Svelte] Error during component init: <Home>
Error: lifecycle functions can only be called while initializing or before preparing a component to resume (i.e. with a reactive statement on "params")
    at onResume (stack-router.js:623)
    at instance (Home.svelte:4)
    at init (index.mjs:1791)
    at new Home (Home.svelte:9)
    at createComponent (svelte-hooks.js:136)
    at Home.targetCmp.$replace (svelte-hooks.js:183)
    at refreshComponent (proxy.js:168)
    at ProxyAdapterDom.rerender (proxy-adapter-dom.js:77)
    at proxy.js:398
    at Array.forEach (<anonymous>)
```

Here is my route component ```Home.svelte``` i am trying to use svelte-stack-router lifecycle hook.
```
<script lang="ts">
    import { onResume, push } from 'svelte-stack-router';

    onResume(() => {
        console.log('onResume')
    })
</script>

<div on:click={() => push('/another')}>Go to another page.</div>
```

Could anyone please tell me how to make it work with Vite HMR?
Thank you

**Comment by cdellacqua** [comment]
I doubt it can be done, HMR re-runs the instructions in the component even if it has already been mounted, thus resulting in that error.

The only thing you can do for now is disable hot reloading. I looked at the Vite.js docs and to support HMR I should implement Vite.js-specific handlers, unfortunately there doesn't seem to be a standardized way to do HMR yet.
