### ISSUE TITLE
how to manually clear cached page's input data?

### ISSUE THREAD

**Issue by ITwrx** [cdellacqua/svelte-stack-router#13]
hi,
I have a page component with a CreateReminder form in it. Currently, after creating one Reminder, when i navigate to the CreateReminder page again (fresh nav using link: i.e. not using back btn, nor due to redirect), it shows the previous Reminder's input in the form. 

I figured the simplest solution would be to just clear the cached input data for that component when the form is submitted, but i'm not seeing any documentation on how to either disable caching for a route completely (not preferred in this case), or how to clear a specific cached route from the cache, preferably with a way to specify only clearing the associated input data, and not the whole component. 

Or, how are we intended to handle forms with this router? I'm new to SPAs, so i could easily be missing something basic.

Thanks

**Comment by cdellacqua** [comment]
Hi,

there are a couple of solutions.

The easiest option is to disable caching on that specific page by calling setResumable(false) as [documented here](https://github.com/cdellacqua/svelte-stack-router#enhanced-lifecycle-functions).
This would however dispose of the form content immediately, therefore going back wouldn’t recover the form state.

Another option is to manually reset the form fields once the submission succeeds, this way the user will always be able to recover the previous state.

In general form handling is a matter that goes beyond the scope of this (any?) router

**Comment by ITwrx** [comment]
ok, thanks

calling `setResumable(false)` in my component does the trick, as i'm already handling the input data on error, etc. i had forgotten about it, because i wasn't sure how/where to use the enhanced lifecycle functions. 

```
//ReminderCreate.svelte
<script>
import { setResumable } from 'svelte-stack-router';

setResumable(false);
</script>
```
