### ISSUE TITLE
Bug using `useHash={false}`

### ISSUE THREAD

**Issue by dtzxporter** [cdellacqua/svelte-stack-router#4]
When hash mode is disabled, refreshing the page (in chrome at least) fails to pick up the proper location (route) and defaults to "/".

I'll try and figure it out, but may be easier for you to debug since you're more familiar with the logic.

**Comment by cdellacqua** [comment]
Thank you for the feedback!

I tried to fix the problem in this commit 0cee780f2adb09745037d19611223e6d542a9905, I tested locally and it seems to work, let me know if it works so that we can close the issue.

You can download the latest version of the package to try it out

**Comment by dtzxporter** [comment]
Works great, thanks for the quick fix!
