### ISSUE TITLE
Can not work with Buble

### ISSUE THREAD

**Issue by easyfrog** [cdellacqua/svelte-stack-router#8]
Can not swap pages when use `@rollup/plugin-buble` plugin.

* with out buble, works perfect!
![withoutbuble](https://user-images.githubusercontent.com/10724325/137146768-44fe01f9-4098-4a33-b0bf-c4e93cb6f20b.gif)

* with the buble, can not change the pages
![withbuble](https://user-images.githubusercontent.com/10724325/137146924-07f1e8dc-0560-4222-9365-a6286b7b5520.gif)

This is the rollup configuration
```
svelte({  							// SVELTE config

    emitCss: false,
    compilerOptions: {
	    accessors: true,
	    dev: !production,
	    css: css => {
		    css.write(destcs, false);
	    }
    }

}),

commonjs(),

buble({
    objectAssign: 'Object.assign',
    transforms: {
	    dangerousForOf: true,
	    asyncAwait: false,
    }
}),

nodeResolve({
    browser: true,
    dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
})

```

**Comment by cdellacqua** [comment]
Do you have any errors in the browser console?

I'm having difficulties reproducing this issue, could you create a repository containing a minimal working example?

**Comment by easyfrog** [comment]
I find the reason. 
It's the limit of Buble plugin.   `for of` and `Set`
<img width="648" alt="iShot2021-10-14 11 54 29" src="https://user-images.githubusercontent.com/10724325/137253246-244bb5f3-f592-4811-95fd-d647cd70e754.png">

buble config needs add `forOf: false`

```
buble({
      objectAssign: 'Object.assign',
      transforms: {
	      dangerousForOf: false,
	      asyncAwait: false,
	      forOf: false,                // needs this
      }
}),
```
